version: '3.6'

services:
  db:
    build: db
    restart: always
    env_file: db/.env
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"

  corenlp:
    build: corenlp
    restart: always
    ports:
      - "9000:9000"

  languagetool:
    build: languagetool
    restart: always
    ports:
      - "8010:8010"

  app:
    build: app
    restart: always
    env_file: app/.env
    volumes:
      - ./app:/src
    depends_on:
      - db
      - redis
      - corenlp
      - memcached
      - languagetool

  nginx:
    build: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - app
