# Generated by Django 2.0.6 on 2018-07-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='outcome_service_url',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='result_sourcedid',
        ),
    ]
