# Generated by Django 2.0.6 on 2018-08-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_app', '0002_auto_20180810_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='hide_excerpt',
        ),
        migrations.AddField(
            model_name='assignment',
            name='show_excerpt',
            field=models.BooleanField(default=True),
        ),
    ]
