# Generated by Django 2.0.6 on 2018-08-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_app', '0004_auto_20180810_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.TextField(null=True),
        ),
    ]
