# Generated by Django 2.0.6 on 2018-08-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_app', '0005_assignment_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='graded_confirmation_text',
            field=models.TextField(default="Your writing has been submitted for human moderation. The 'grade' will normally appear within 7 days of submission."),
        ),
        migrations.AddField(
            model_name='assignment',
            name='show_retry_button',
            field=models.BooleanField(default=True),
        ),
    ]
