# Generated by Django 2.0.6 on 2018-08-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='checks',
            field=models.IntegerField(default=11111),
        ),
        migrations.AddField(
            model_name='assignment',
            name='hide_excerpt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='model_answers',
            field=models.TextField(null=True),
        ),
    ]
