branch-defaults:
  master:
    environment: scriba-prod
    group_suffix: null
global:
  application_name: scriba
  branch: null
  default_ec2_keyname: scriba-aws-eb-ssh
  default_platform: Python 3.6
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
